version: '3.9'

services:
  userauth:
    image: dlwhitehurst/userauth:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - PORT=3001
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/userauth
    command: yarn start

  personal:
    image: dlwhitehurst/personal:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - USERAUTH_SERVER_PORT_URL=http://myhost:3001
      - PORT=3002
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/personal
    command: yarn start

  medical:
    image: dlwhitehurst/medical:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - USERAUTH_SERVER_PORT_URL=http://myhost:3001
      - PORT=3003
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/medical
    command: npm start

  financial:
    image: dlwhitehurst/financial:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - USERAUTH_SERVER_PORT_URL=http://myhost:3001
      - PORT=3004
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/financial
    command: yarn start

  administration:
    image: dlwhitehurst/administration:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3005:3005"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - USERAUTH_SERVER_PORT_URL=http://myhost:3001
      - PORT=3005
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/administration
    command: npm start

  legal:
    image: dlwhitehurst/legal:0.1.5-align
    extra_hosts:
      - "myhost:172.25.78.22"
    restart: always
    ports:
      - "3006:3006"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mariadbAdmin123
      - DB_SCHEMA=virtualyou
      - USERAUTH_SERVER_PORT_URL=http://myhost:3001
      - PORT=3006
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/legal
    command: yarn start

  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadbAdmin123
      - MYSQL_DATABASE=virtualyou
    ports:
      - 3306:3306

