version: '3.9'

services:
  db:
    image: mariadb:10.5
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadbAdmin123
      - MYSQL_DATABASE=virtualyou
    ports:
      - 3306:3306

